version: "3"

vars:
  SPHINX_SOURCE: docs/source
  SPHINX_BUILD: docs/_build
  API_OUT: docs/source/api/generated

tasks:
  install:
    desc: Install all dependency groups via uv
    cmds:
      - uv sync --all-groups

  # Optional legacy task (kept for manual full module dump). Prefer autosummary.
  apidoc:
    desc: (Optional) Generate static API rst stubs with sphinx-apidoc
    cmds:
      - mkdir -p {{.API_OUT}}
      - uv run sphinx-apidoc -o {{.API_OUT}} chemotools

  docs:html:
    desc: Build English HTML documentation
    cmds:
      - uv run sphinx-build -b html {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/html -j auto

  docs:html-es:
    cmds:
      - uv run sphinx-build -b html -D language=es -D html_theme_options.switcher.version_match=es {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/html/es -j auto

  docs:html-zh:
    cmds:
      - uv run sphinx-build -b html -D language=zh_CN -D html_theme_options.switcher.version_match=zh_CN {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/html/zh_CN -j auto


  docs:html-all:
    desc: Build all language variants (en, es, zh_CN)
    cmds:
      - task: docs:html
      - task: docs:html-es
      - task: docs:html-zh

  docs:gettext:
    desc: Extract gettext catalogs
    cmds:
      - uv run sphinx-build -b gettext {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/gettext -j auto

  docs:update-translations:
    desc: Update .po files for es and zh_CN
    deps: [docs:gettext]
    cmds:
      - uv run sphinx-intl update -p {{.SPHINX_BUILD}}/gettext -l es -l zh_CN

  docs:check:
    desc: Build English docs treating warnings as errors (CI quality gate)
    cmds:
      - uv run sphinx-build -b html {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/html -W -j auto

  serve:
    desc: Live-reload English docs on port 8003 (avoiding port conflicts)
    cmds:
      - uv run sphinx-autobuild {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/html --watch chemotools --ignore "{{.SPHINX_BUILD}}/*" --ignore "{{.API_OUT}}/*" --port 8003

  serve:en:
    desc: Live-reload English docs on port 8003 (avoiding port conflicts)
    cmds:
      - uv run sphinx-autobuild {{.SPHINX_SOURCE}} {{.SPHINX_BUILD}}/html --watch chemotools --ignore "{{.SPHINX_BUILD}}/*" --ignore "{{.API_OUT}}/*" --port 8003

  serve:zh:
    desc: Serve Chinese docs locally
    cmds:
      - task: docs:html-zh
      - echo "Chinese docs available at http://localhost:8001"
      - cd {{.SPHINX_BUILD}}/html/zh_CN && python3 -m http.server 8001

  serve:es:
    desc: Serve Spanish docs locally  
    cmds:
      - task: docs:html-es
      - echo "Spanish docs available at http://localhost:8002"
      - cd {{.SPHINX_BUILD}}/html/es && python3 -m http.server 8002

  clean:
    desc: Remove build artifacts and generated API stubs
    cmds:
      - rm -rf {{.SPHINX_BUILD}} {{.API_OUT}}

  dev:
    desc: Install dependencies then launch live docs server
    cmds:
      - task: install
      - task: serve
