name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme sphinx-copybutton sphinx-intl

      - name: Generate translations
        run: |
          cd docs
          sphinx-build -b gettext source source/locale/gettext
          sphinx-intl update -p source/locale/gettext -l es -l zh

      - name: Build documentation (all languages)
        run: |
          cd docs
          # Build English version
          make html
          # Build Spanish version
          sphinx-build -b html -D language=es source _build/html/es
          # Build Chinese version
          sphinx-build -b html -D language=zh source _build/html/zh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4